# Generated by Django 4.2.5 on 2023-09-07 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Campaign ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Campaign Name')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('preview_text', models.TextField(verbose_name='Preview Text')),
                ('article_url', models.URLField(verbose_name='Article URL')),
                ('html_content', models.TextField(verbose_name='HTML Content')),
                ('plain_text_content', models.TextField(verbose_name='Plain Text Content')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.campaign', verbose_name='Campaign ID')),
                ('campaign_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_name', to='manager.campaign', to_field='name', verbose_name='Campaign Name')),
                ('subscriber_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.subscriber', verbose_name='Subscriber Email')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('subscriber_email', 'campaign_id', 'campaign_name'), name='unique_subscription'),
        ),
    ]
