# Generated by Django 4.2.5 on 2023-09-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='unique_subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='campaign_id',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('subscriber_email', 'campaign_name'), name='unique_subscription'),
        ),
    ]
